### ISSUE TITLE
Update richness figure colors

### ISSUE THREAD

**Issue by jcoliver** [Big-Biodiversity-Collaborative/SwallowtailClimateChange#102]
Two things to try/consider:

- [x] Use a different color palette (currently low is yellow and high is green). Try the inferno palette as a first start (often used by eBird).
- [x] For areas where we have predictions and the predicted number of species is zero, use a markedly different color.
- [ ] (stretch) Consider adding polygon(s) around those areas with >=4 species, since we talk about these areas in manuscript.

**Comment by ezylstra** [comment]
Updated colors. Used the eBird abundance/inferno palette for richness, with a light gray for areas with 0 species. Used a eBird-like palette for the richness change figures, with blue for positive values and red for negative values. 

The 3rd item (denoting "hotspots") proved a bit difficult.  There are lots of very small hotspots, so using a polygon to delineate those areas wasn't possible.  Alternatively, we talked about binning values, having one color for 0 spp, one for 1-3 spp, and one for 4-7 spp. However, I didn't like that either and we're essentially throwing out information. Maybe this isn't necessary or if so, could put in supplement.

**Comment by jcoliver** [comment]
Closing for now; polygons around high richness areas did not add to figure.

**Comment by jcoliver** [comment]
For richness delta, try three-color palette as used for single species deltas showing loss "#fc8d59", stable "#ffffbf", and gain "#2c7bb6".

**Comment by jcoliver** [comment]
Delta plots just don't "pop" if that orange/blue palette is used. Keep red/blue palette.
