### ISSUE TITLE
Create single-species six-panel maps for manuscript

### ISSUE THREAD

**Issue by jcoliver** [Big-Biodiversity-Collaborative/SwallowtailClimateChange#103]
For two species (currently _P. indra_ and _P. cresphontes_), we would like a pair of six panel figures for the supplemental information:

- [x] Predicted distributions for each future time period (2041-2070 and 2071-2100) and each climate scenario (2-4.5, 3-7.0, 5-8.5).
- [x] Predicted change from current for each future time period and each climate scenario.

For each of the above, columns (2) are time period and rows are climate scenarios (3).

**Comment by ezylstra** [comment]
Done for both species. Created new script in summary folder (create-supplement-object.R) and saved four 6-panel figures to output/manuscript folder (eg, papilio_indra-overlap-6panel.png)
