### ISSUE TITLE
Estimate data reduction with temporal restriction

### ISSUE THREAD

**Issue by jcoliver** [Big-Biodiversity-Collaborative/SwallowtailClimateChange#23]
When restricting observational data to 2000-2018, it would be good to know how much of a reduction (% per species) of data occurs. Ideally this information could be sent to a log of some sorts...

**Comment by ezylstra** [comment]
Place this script in the src/data folder

**Comment by jcoliver** [comment]
Ideally, we should have a script that interrogates the downloaded GBIF data (in data/gibf.zip) and produces a table with the following information:

| Species | Total occurrences | Post-2000 Occurrences |
|:-|-:|-:|
| Alnus rubra | 2876 | 2378 |
| ... | ... | ... |
| Papilio rumiko | 3711 | 3555 |
| ... | ... | ... |

The data files (one for each species) are in the zip archive, so the first part of a script addressing this would likely start with something like:
```
  unzip(zipfile = "data/gbif.zip")
```
An example of iterating over each data files can be found in the script src/data/data-gbif-qa.R.

**Comment by ezylstra** [comment]
This makes sense to me.  I'll start working on it this week.

**Comment by ezylstra** [comment]
I added a new script to do this.  Will need to run with the full set of gbif data in the zip file (haven't done this). I did have one question about whether we need to remove the data/gbif folder that's created when we unzip (see comment at end of script).  I know files in that folder are included in .gitignore, but not sure if we should remove the folder itself after running this script.

**Comment by ezylstra** [comment]
Didn't mean to close the issue yet!  Should probably wait until it's reviewed and question above is resolved.

**Comment by ezylstra** [comment]
Addressed in a6f86c0
