### ISSUE TITLE
Update bash scripts so they identify species-specific datafiles based on accepted name

### ISSUE THREAD

**Issue by ezylstra** [Big-Biodiversity-Collaborative/SwallowtailClimateChange#28]
Now that filenames for species-specific csvs reflect species' accepted names, we need to update bash scripts so that we use the "accepted_name" column in gbif-reconcile.csv to identify the correct csv.

**Comment by ezylstra** [comment]
Will eventually need to also update several R scripts in the summary folder so they reference accepted names in gbif-reconcile and insect-host csvs.

**Comment by ezylstra** [comment]
Updated bash shell scripts.  Will create a separate issue for updating summary scripts.

**Comment by jcoliver** [comment]
Looks like only one spot needed an update (functions/overlap_raster.R). Addressed in 5ca1166.
