### ISSUE TITLE
Update README to include development and ensemble folders

### ISSUE THREAD

**Issue by ezylstra** [Big-Biodiversity-Collaborative/SwallowtailClimateChange#30]

**Comment by ezylstra** [comment]
Dependencies needed (or we think we will need) for scripts in the development folder that weren't already listed:
terra
randomForest

Also, to run maxent model: must first download the program from http://www.cs.princeton.edu/~schapire/maxent/. 
Put the file 'maxent.jar' in the 'java' folder of the 'dismo' package. 
That is the folder returned by system.file("java", package="dismo").

**Comment by jcoliver** [comment]
Addressed, for the most part, in 5484717
