### ISSUE TITLE
Identify GBIF records for which climate data are unavailable

### ISSUE THREAD

**Issue by ezylstra** [Big-Biodiversity-Collaborative/SwallowtailClimateChange#31]
All of the new presence-absence datasets have some presence records for which all predictor variables are NA.  Looks like these locations are incorrect or imprecise (off the coast or actually on land, but near water in an area like Vancouver).  Probably want to exclude these records when creating pa datasets to ensure record counts (and weighting) are correct.

**Comment by jcoliver** [comment]
Nice. We might build in some QA in the background point generation to identify all the _X_ background points that do not have corresponding bioclimate data, then do _another_ round of background sampling of _X_ additional points. Rinse and repeat until _X = 0_

**Comment by ezylstra** [comment]
Well, I'm not seeing that issue with the background points (at least for the 4 species I tried) - probably because we're using a bioclim raster as a mask when sampling points. If it's just the presence points, we could remove these observations at a couple different points in the workflow. Right now, I'm thinking it might be best to do that in data-gbif-qa.R, before dumping all the csvs in a zip file.

**Comment by jcoliver** [comment]
Oh, right, _presence_ points. Best to just drop as described in OP. :)

**Comment by ezylstra** [comment]
Sounds good.  I'll assign this issue to me and hopefully make changes to data-gbif-qa.R sometime this week.

**Comment by ezylstra** [comment]
Made changes to data-gbif-qa.R, and updated gbif.zip. See 57d90bf
