### ISSUE TITLE
Calculate percent of contemporary range occupied 

### ISSUE THREAD

**Issue by jcoliver** [Big-Biodiversity-Collaborative/SwallowtailClimateChange#42]
Current summary calculations only compare total areas of contemporary vs. forecast range. Would be useful to consider how much of the _current_ range will be suitable under forecast climate models.

**Comment by jcoliver** [comment]
Addressed (for glm) in 10219c2. On hold for now, as it is not clear if this should be done for individual species distribution methods or for consensus distributions.

**Comment by ezylstra** [comment]
Now addressed (for consensus distributions) in 1d58d48

**Comment by ezylstra** [comment]
This is being calculated in [summary-2-compare-ranges.R](https://github.com/Big-Biodiversity-Collaborative/SwallowtailClimateChange/blob/main/src/summary/summary-2-compare-ranges.R)
