### ISSUE TITLE
Identify minimum number of records for SDMs

### ISSUE THREAD

**Issue by ezylstra** [Big-Biodiversity-Collaborative/SwallowtailClimateChange#43]
Probably need to add a line to template SDM scripts that aborts (doesn't create an SDM) when the number of records that would be included in the training dataset is below some pre-determined minumum.

There are some examples out there of SDMs being built on <20 or even <10 records. 
 However, [van Proosdij et al. 2015 ](https://onlinelibrary.wiley.com/doi/full/10.1111/ecog.01509) used simulations and test cases to evaluate how the number of records affects SDM accuracy. For their test case, they needed a minimum of 14 records for species with small geog ranges and 25 records for widespread species. 

To be conservative, we could say that we need a minimum of filtered 40 records for each species (which would mean that 32 records would remain in the training dataset)?

**Comment by ezylstra** [comment]
Certainly seems like a reasonable place to start.  I'll go through and add this condition to the template-SDM scripts this week.

**Comment by ezylstra** [comment]
@jcoliver: Not sure the best place to stop the process if the (total) number of observations is <40.  I had suggested we make changes to the template-SDM scripts, but I don't think that's the most efficient way of doing things.

In src/data/gbif-3-presence-absence.R we only write a csv to file if a species has >= 10 filtered records. We could change this to 40 (and then clean up the run-all-SDM-XXX-scripts.R a bit). The only downside with this approach is that if we want to change that minimum number, we have to create new background points for each species and save new presence-absence csvs to file.  

Currently, in run-all-SDM-XXX-scripts.R, we read in the csv file with pres-abs data for a species and if there are < 50 filtered records we don't run the SDM. We could change this to 40. The downside with this approach is that if we run species-specific SDM scripts (outside of the run-all script), it'll create a SDM regardless how many records are on file.

Thoughts?

**Comment by jcoliver** [comment]
I like option 1 (only writing presence / absence file if there are 40 records remaining after all the filtering & thinning). I'm OK having to re-create the p/a files every time we change the minimum. Let's just plan to not change it much. :D

Would probably be a good idea to indicate minimum number of observations up at the top of the script (i.e. define something like `min_obs` up by `replace` and `verbose` declarations and use that in the conditional on line ~73 instead of the integer value itself). Same goes for number of absence points, too.

**Comment by ezylstra** [comment]
Changed the gbif-3-presence-absence.R script to specify a minimum of 40 filtered records 7b91f9c.

Also worked on the run-all-SDM scripts:
- removed the 50 observation minimum
- generalized scripts by adding objects like sdm_method
- created new run-all-SDM scripts for new methods (brt, lasso, maxent-tune)
