### ISSUE TITLE
Decide whether to include all climate variables in SDMs

### ISSUE THREAD

**Issue by ezylstra** [Big-Biodiversity-Collaborative/SwallowtailClimateChange#45]
In the run_glm function we didn't include bio3 and bio7 (because they're functions of other variables?).  Good idea to become more familiar with the 19 possible variables and decide whether to exclude these and/or other variables from all SDMs?

**Comment by jcoliver** [comment]
I would love to be able to use inheritance so we could create a function `run_sdm()` that included an argument with the variables we include by default (i.e. drop the four quarterly ones we discussed). All `run_[sdm_method]()` functions would then be a sub-class of that `run_sdm()` function and therefore have the arguments "inherited", meaning we wouldn't have to duplicate the same list of arguments in function definitions for each `run_[sdm_method]()` function.

But. I don't know how to do this in R. Or if it is even possible.

An alternative would be to replace the proliferation of `run_[sdm_method]()` functions with a single `run_sdm()` function that takes an argument, say, `sdm_method` (values of "rf", "brt", "maxent", etc.) and uses conditionals or case statements to decide which SDM method to use. This would align with the behavior of `predict_sdm()`.

But still on the fence and open to other ideas.

**Comment by ezylstra** [comment]
I've been thinking about this too, but can't figure out a clever way of creating a single `run_sdm()` function.  Unlike the `predict_sdm()` function, where all models use predict just with different arguments, the `run_[sdm_method]()` functions are very different.  (compare `run_maxent_tune()` with `run_gam()` for example).  

Working on it...

**Comment by jcoliver** [comment]
Another option would be to create a file (data/included-predictors.csv?) with two columns: one with the variable name and one with a logical indicating whether or not to include in model estimation/prediction.

| var_name | include |
| ------------- | ---------- |
| bio1          | TRUE  |
| bio2          | TRUE  |
| bio3          | FALSE  |

We'd then read in this file within each `run_[sdm_method]()` call, build the model formula with `paste()` and go from there.

**Comment by ezylstra** [comment]
Thats funny, because it's exactly what I've created in a development version on my machine :)

**Comment by ezylstra** [comment]
Implemented above changes.  From here on out, if we want to include/exclude different climate variables in SDMs, we should only need to change climate-variables.csv
