### ISSUE TITLE
Decide whether to keep glms in the mix

### ISSUE THREAD

**Issue by ezylstra** [Big-Biodiversity-Collaborative/SwallowtailClimateChange#46]
In its current form, our glm SDM has no regularization and only includes linear terms for each climate variable.  Is it worth keeping this SDM in the mix if we have a lasso model (that allows for quadratic terms) and a GAM?  Note that lasso and GAM models performed better than a GLM in Valavi et al. 2021.

**Comment by jcoliver** [comment]
I suspect vanilla GLMs will not make the final cut for the paper, but I'm inclined to keep the workflow kicking around for educational/training purposes.

**Comment by ezylstra** [comment]
For record-keeping purposes, I updated the run_glm() function and associated template scripts so we can keep glms in our pile of SDMs.  I did, however, add bits so we're standardizing all the (linear) effects in the glm.
