### ISSUE TITLE
Explore how problematic it may be to drop species with <40 filtered records

### ISSUE THREAD

**Issue by ezylstra** [Big-Biodiversity-Collaborative/SwallowtailClimateChange#48]
Wondering whether we might underestimate overlap and butterfly predicted ranges if we don't create any kind of species distribution model for host plants with few occurrence records (especially for butterflies with few host plants).  

For host plants with < 40 filtered records, I could imagine using an MCP to coarsely identify the species current range.  However, it's unclear how we could then project changes in the species' range.

Maybe start by exploring how often this occurs and when/where it might bias a butterfly's predicted range?

**Comment by jcoliver** [comment]
First step would be to use data/gibf-pa-summary.csv to see what proportion of each insect species' diet would be excluded with this 40 obs threshold.

**Comment by jcoliver** [comment]
Pretty good shape:

| insect | num_filtered | included | total_hosts | included_hosts | host_prop |
|:-|-|-|-|-|-|
| Papilio appalachiensis | 98 | TRUE | 1 | 1 | 1.0000000 |
| Papilio aristodemus | 3 | FALSE | 2 | 2 | 1.0000000 |
| Papilio brevicauda | 158 | TRUE | 8 | 8 | 1.0000000 |
| Papilio canadensis | 5325 | TRUE | 20 | 19 | 0.9500000 |
| Papilio cresphontes | 5308 | TRUE | 4 | 4 | 1.0000000 |
| Papilio eurymedon | 2144 | TRUE | 5 | 5 | 1.0000000 |
| Papilio glaucus | 14990 | TRUE | 26 | 26 | 1.0000000 |
| Papilio indra | 205 | TRUE | 21 | 13 | 0.6190476 |
| Papilio machaon | 448 | TRUE | 39 | 13 | 0.3333333 |
| Papilio multicaudata | 2244 | TRUE | 15 | 15 | 1.0000000 |
| Papilio palamedes | 1642 | TRUE | 2 | 2 | 1.0000000 |
| Papilio polyxenes | 12013 | TRUE | 37 | 32 | 0.8648649 |
| Papilio rumiko | 1811 | TRUE | 5 | 4 | 0.8000000 |
| Papilio rutulus | 3487 | TRUE | 28 | 28 | 1.0000000 |
| Papilio troilus | 7316 | TRUE | 6 | 6 | 1.0000000 |
| Papilio zelicaon | 2171 | TRUE | 44 | 38 | 0.8636364 |

_Papilio machaon_ has a bunch of introduced hosts listed, and _P. indra_ likes shitty little rare desert plants that everyone ignores.

**Comment by jcoliver** [comment]
Code for table above in src/data/gbif-check-filter.R and output in data/gbif-filter-summary.csv. See 1a119d6.
