### ISSUE TITLE
Mask out Great Lakes

### ISSUE THREAD

**Issue by jcoliver** [Big-Biodiversity-Collaborative/SwallowtailClimateChange#49]
Several predictions (current and forecast climate models) are predicting presence in the lakes, which is not realistic. We need to exclude these data. Probably best way is to do the masking at the climate variable stage - that is, when creating climate data, we should drop (i.e. assign values of `NA` to cells) in the Great Lakes.

**Comment by ezylstra** [comment]
Found a shapefile with inland water bodies [here](https://www.naturalearthdata.com/downloads/10m-physical-vectors/10m-lakes/). It's the same source as that used by [Kass et al. 2022 (Sci Adv)](https://www.science.org/doi/10.1126/sciadv.abp9908). 

Put the shapefile in development/data,  in a folder labeled "lakes". 

Created a test script (`development/src/mask-lakes-testing.R`) to evaluate methods for masking out Great Lakes and other large inland water bodies. See 06c4b21.

**Comment by jcoliver** [comment]
Current thought is to apply this masking in the climate data preparation steps. Presence/absence of climate data is used to make several downstream decisions (background points, predicted presence/absence), so masking of Great Lakes should _only_ need to occur in the climate data preparation stage.

**Comment by jcoliver** [comment]
Bulk of work done in d6f3f05 (currently on separate branch, 230109-mask-great-lakes; will merge soon).
