### ISSUE TITLE
Develop consensus approach

### ISSUE THREAD

**Issue by jcoliver** [Big-Biodiversity-Collaborative/SwallowtailClimateChange#50]
Identify approach to combine predictions from multiple species distribution model methods into a single "consensus" approach. First pass would be a majority-rules based on presence / absence thresholds from each SDM method.

**Comment by ezylstra** [comment]
Created a test version of a script that creates consensus distributions for any number of species and climate models. See eb05c7b

**Comment by ezylstra** [comment]
Modified create-consensus-distributions script and moved to the src/summary folder. See 4ab118f. @jcoliver: feel free to move if you think this script fits better elsewhere.

**Comment by jcoliver** [comment]
Nice. Probably worth while to save distribution rasters with terra so they are SpatRasters, to reduce dependency on raster package, but that's a separate issue.
