### ISSUE TITLE
Save distribution rasters with terra so they are SpatRasters

### ISSUE THREAD

**Issue by jcoliver** [Big-Biodiversity-Collaborative/SwallowtailClimateChange#54]
Currently, distribution rasters (.rds files saved to output/distributions) are `raster::RasterLayers`, but in the migration to use terra, it would be better if they were saved as `terra::SpatRaster` objects. The heavy lifting for this change is going to be in functions/predict_sdm.R, and there might be some adaptation necessary in the templates/template-distribution-[sdm method].R files, too.

**Comment by ezylstra** [comment]
I think this is a good idea. I can start to work on this over the break.

**Comment by ezylstra** [comment]
Done (over a bunch of different commts, starting with 21dcb8d6 on 29 Dec 2022).  Changes were needed in several different scripts.
