### ISSUE TITLE
Investigate density envelope for S. hookeriana

### ISSUE THREAD

**Issue by jcoliver** [Big-Biodiversity-Collaborative/SwallowtailClimateChange#58]
The density envelope for _S. hookeriana_ is including an observation that is the farthest north and west, while including other points. The observation itself it a little troublesome (DNA soil sample, [https://www.gbif.org/occurrence/3972239300](https://www.gbif.org/occurrence/3972239300)), but should (theoretically) be excluded through the 95% envelope filtering approach.

For now manually removed the point before subjecting to presence/absence creation.

**Comment by jcoliver** [comment]
Could try density estimate from ks package. _S. hookeriana_ is usually at index 147.

**Comment by ezylstra** [comment]
I'll do a few more checks tomorrow, but on first glance with _S. hookeriana_, the ks package does not seem to have the same problem the MASS package does.  Assuming no other problems pop up, it would also be nice to use the ks package since the code is soooo much simpler!  Something like this:
```
library(ks)
mat <- as.matrix(data[, c("longitude", "latitude")])
band <- Hscv(mat)
fhat <- ks::kde(mat, H = band)
data$ks_pred <- predict(fhat, x = mat)
data$ks_envelope <- ifelse(data$ks_pred >= fhat$cont["5%"], 1, 0)

```

**Comment by ezylstra** [comment]
@jcoliver: could use your help. Weird stuff going on.  I'm going to attach figures with 95% KDEs based on the ks package and MASS package for two species.  These species aren't special -- they're literally just a couple of the first species I tested.  (Note for figures: For the ks package, I tried 5 different bandwidths (ie, types of smoothing). When I count up the number of observations that were outside the MASS envelopes for either species, it's way fewer than you'd expect (<1% of observations).  When I count up the number of observations that were outside ks envelopes, it's 5% of observations. 
1) I haven't sorted through all the MASS code, so I'm not sure why so few observations are being removed. 
2) It's very unclear to me what the appropriate bandwidth might be for the ks KDEs. We may even think about using a higher cutoff, like 97 or 98% if the sole purpose to remove outliers.

Any thoughts would be appreciated!
![P_rumiko_MASS](https://user-images.githubusercontent.com/41200620/220455896-0f1eac3c-3bbe-4079-b671-8841eb15c2ff.jpeg)
![P_rumiko_ks_kdes](https://user-images.githubusercontent.com/41200620/220466693-084d4f60-3b95-42ff-ba16-43f1d4b3a348.jpeg)
![Ptelea_trifoliata_MASS](https://user-images.githubusercontent.com/41200620/220455963-842af946-3ced-41ef-aa7d-faa76b5882cd.jpeg)
![Ptelea_trifoliata_ks_kdes](https://user-images.githubusercontent.com/41200620/220466724-6555ec61-ba9c-4f04-b1e5-41f13002d4bb.jpeg)

**Comment by jcoliver** [comment]
Fun! My initial thought is that the hbcv & hns bandwidths are the most appropriate (the other three look "overfit" for lack of a better term). Maybe the next comparisons are hbcv & hns at 98% (to compare with the 95%, above).

**Comment by ezylstra** [comment]
I think I agree about the the smoothing parameters - I'll play around with the percentages next and let you know what things look like. By the way, were you seeing the same thing with the MASS KDEs, where they were removing considerably <5% of observations?

**Comment by jcoliver** [comment]
Can't say I looked too closely at how many were excluded. I can rationalize to myself how the number removed would depart from expected based on envelope boundary estimation...

**Comment by ezylstra** [comment]
With respect to bandwidth selectors in the ks package, I think the hns (normal scale) and biased cross validation (hbcv) are producing pretty similar results. However, the hns option runs much faster.  Here are 95% and 98% KDEs with H = hns for 3 species (black dots are outside the 98% KDE, gray dots are in).  Leaning toward the 98% envelope.  For species with the minimum number of records to use the KDE filter (n = 100), that means only 2 observations would be filtered out. For species with 1000 observations, 20 would be filtered out. 
![Ptelea_trifoliata_hns](https://user-images.githubusercontent.com/41200620/221035949-c28b8f25-de98-4b45-bdee-298ad5f24b5c.jpeg)
![Papilio_rumiko_hns](https://user-images.githubusercontent.com/41200620/221036005-92b13029-c779-4672-a737-3e67c9565c48.jpeg)
![Salix_hookeriana_hns](https://user-images.githubusercontent.com/41200620/221036022-089f01f5-e61d-472a-b301-af00f794fde4.jpeg)

**Comment by jcoliver** [comment]
hns at 98% sounds great, if for no other reason than it tosses that godforsaken northern Alaska _S. hookeriana_ sample. (although the next GBIF pull will exclude it anyway).

**Comment by ezylstra** [comment]
I'm on board with that.  I can get that implemented in the gbif-2-filter script soon and then I'll proceed through the rest of the workflow as we talked about.  I may not get this today or tomorrow, but if you're in a hurry let me know and I can push this to the top of the pile.

**Comment by ezylstra** [comment]
Implemented this approach (98% KDEs based on normal scale smoothers) in c38da62.
