### ISSUE TITLE
Add try/(catch) to downloading function

### ISSUE THREAD

**Issue by jcoliver** [Big-Biodiversity-Collaborative/SwallowtailClimateChange#59]
Downloading data from GBIF could be wrapped in `try()` to catch timeout errors; also write to logs when maximum number of attempts is reached (and failed). Logs can then be checked for things to re-attempt downloading.

**Comment by jcoliver** [comment]
See the [query_gbif()](https://github.com/Big-Biodiversity-Collaborative/west-virginia-white/blob/main/functions/query_gbif.R) function in the [West Virginia White project](https://github.com/Big-Biodiversity-Collaborative/west-virginia-white).

**Comment by jcoliver** [comment]
Added this and went ahead re-running the rest of the data pipeline (download, filter, presence/absence). Will take a look later at delta of records. @ezylstra

**Comment by ezylstra** [comment]
@jcoliver. Something weird happened with the shapefiles zip so we didn't have 5 files for each species. Often the .prj file was missing.  I re-ran gbif-3-presence-absence.R after clearing out anything in my local gbif/shapefiles and gbif/presence-absence folders and now the shapefiles.zip seems to be complete.  Not sure what happened, but make sure to pull the latest version with new zips before you work on anything.  Eventually, we may need to add something to gbif-3-presence-absence.R that would clear out any existing files (assuming we want to replace them), but this isn't urgent if we're both working with the latest version and we're not running src/data scripts.
