### ISSUE TITLE
Different extents for distribution rasters

### ISSUE THREAD

**Issue by ezylstra** [Big-Biodiversity-Collaborative/SwallowtailClimateChange#61]
Having trouble running `create-consensus-rasters.R` because the extents of distribution rasters for a given species & set of climate data don't match.  Not sure why this is happening since all SDMs use the same predict_sdm() function that delineates prediction areas using a shapefile specific to each species. Couple notes based on the 2 butterflies I looked at:
- Extent of lasso and rf distributions (and maybe maxent) seem to be bigger?
- Didn't have this problem with P. rumiko for the current climate data.  Is it possible we used outdated shapefiles when creating the SDMs/distributions?

**Comment by jcoliver** [comment]
We could add in functionality that will extend rasters as necessary (with the caveat that we should still check to see if the different predictions really should be different in extent). We used the raster approach (`raster::extend()`) in the `stack_rasters()` function (lines 56-57 and elsewhere); I think `terra::extend()` has similar functionality. Perhaps when predicted distributions are read into memory (line 66 of create-consensus-rasters.R).

**Comment by ezylstra** [comment]
Yup, I think the methods you mentioned would work (I think I haven't something similar built in when we're combing rasters for butterflies and their hostplants?).  I'll spend some time investigating this after today, because I'm not sure why that's happening.  Plus, I want to be sure that the extents of those predicted distributions match what we have written for the methods section.

**Comment by jcoliver** [comment]
Since I mucked around with the MCP creation in [src/data/gbif-3-presence-absence.R](https://github.com/Big-Biodiversity-Collaborative/SwallowtailClimateChange/blob/main/src/data/gbif-3-presence-absence.R), it wouldn't hurt to make sure those are still acting the way they should, too.

**Comment by ezylstra** [comment]
Sounds good.  I'll try to spend time on this on Monday.

**Comment by ezylstra** [comment]
Created new consensus and overlap rasters with SDMs and distributions for P. rumiko and P. cresphontes groups from HPC run earlier this week -- no more errors with raster extents! Fixed a minor issue in the `summarize-overlap-rasters.R` script (see 98e4da8), and things look good to go.  

We'll definitely need further discussions about how we want to summarize changes in predicted distributions, but for now things are running.
