### ISSUE TITLE
Improve raster maps

### ISSUE THREAD

**Issue by jcoliver** [Big-Biodiversity-Collaborative/SwallowtailClimateChange#64]
Can we improve the raster maps (specifically overlap rasters and delta rasters) so the buffer area doesn't dictate the shape of the map? This may require the recruitment of some North American shapefile (or something of that ilk). Maybe the geodata package has something?

**Comment by jcoliver** [comment]
Has @ezylstra done this? :thinking:

**Comment by ezylstra** [comment]
Kinda... Quick question for @jcoliver: do we want the delta and overlap maps to always have the political boundaries, or should it be an option available with an argument to those functions like `boundaries = TRUE`?

**Comment by jcoliver** [comment]
Addressed for overlap maps in [acaa869](https://github.com/Big-Biodiversity-Collaborative/SwallowtailClimateChange/commit/acaa8697ab93cac9d8f80841b2d379d6f6623937) and delta maps in [aee7e08](https://github.com/Big-Biodiversity-Collaborative/SwallowtailClimateChange/commit/aee7e084cab4578b8dea11b10eb751a5f011a3d5).
