### ISSUE TITLE
Decide on evaluation criteria/on to determine which models are good enough

### ISSUE THREAD

**Issue by jcoliver** [Big-Biodiversity-Collaborative/SwallowtailClimateChange#65]
After running five-fold training/testing splits, will need to evaluate performance. Possible metrics include (not limited to and may have more than one):

+ AUC
+ Mean Absolute Error
+ ...

**Comment by jcoliver** [comment]
Current efforts focusing on null model approach, using ENMEval. See Kass et al. 2020 for details [https://onlinelibrary-wiley-com.ezproxy4.library.arizona.edu/doi/full/10.1111/ecog.04886](https://onlinelibrary-wiley-com.ezproxy4.library.arizona.edu/doi/full/10.1111/ecog.04886).

**Comment by ezylstra** [comment]
Scrapped null model approach. Decided to use ensemble with weighted average of suitability values.
