### ISSUE TITLE
New predictions approach

### ISSUE THREAD

**Issue by ezylstra** [Big-Biodiversity-Collaborative/SwallowtailClimateChange#71]
- [x] Create template R script for each species
- [x] Update predict_sdm function
- [x] Create bash script
- [x] Create output/suitabilities folder

For each time period
1. Predict suitability based on each SDM (save only current time period: suitabilities/genus_species-[sdm]-current.rds)
2. Create raster with weighted average of suitability values (save: suitabilities/genus_species-ensemble-[time].rds)
3. Calculate threshold value
4. Create raster with predicted distribution (save: distributions/genus_species-distribution-[time].rds)

**Comment by ezylstra** [comment]
@jcoliver I think things are finished and working. I also closed an separate issue that was created just to update predict_sdm.

**Comment by jcoliver** [comment]
As with the other two bash-builders, want to test this out before closing the issue. @ezylstra
