### ISSUE TITLE
Assess whether ecospat and flexsdm packages still needed

### ISSUE THREAD

**Issue by ezylstra** [Big-Biodiversity-Collaborative/SwallowtailClimateChange#78]
If we decide that the only SDM evaluation metric we need for all 5 SDMs is TSS, then we may not need ecospat and flexsdm packages anymore.

**Comment by ezylstra** [comment]
@jcoliver `flexsdm` package is needed to calculate TSS values and thresholds for CV models as part of `evaluate_sdm()` function. `ecospat `is also used in `evaluate_sdm()`, but only to calculate CBI, which we're not using to evaluate or weight models - we're using TSS instead.  We could change the `evaluate_sdm()` function so we're no longer including a column for CBI values in table with evaluation metrics (and remove `ecospat` from the list of dependencies), but maybe best to keep in for now in case? 

That said, I did remove both from the list of required packages in templates 2 and 3 because they're not used in those scripts (3fc121db)

**Comment by jcoliver** [comment]
I think we are good where we are at - flexsdm and ecospat no longer depend on all those retired geospatial packages, so it seems like something we don't have to worry about anymore.
