### ISSUE TITLE
Update 2070 predictions to use same buffer size as 2040

### ISSUE THREAD

**Issue by jcoliver** [Big-Biodiversity-Collaborative/SwallowtailClimateChange#87]
Update template-3-predict.R to use a single buffer size (350 km) for forecast suitabilities and distributions.

**Comment by ezylstra** [comment]
Made changes to template-3 so we're using a 350 km buffer for all time periods (f1b676a). Will keep this issue open until I update summary scripts and check for any other downstream effects of changing the buffer size.

**Comment by ezylstra** [comment]
Just checked, and I'm not seeing any other issues with changing the buffer size.  Downstream code didn't need the buffer width specified.
