### ISSUE TITLE
Extract variable importance information from individual SDM

### ISSUE THREAD

**Issue by jcoliver** [Big-Biodiversity-Collaborative/SwallowtailClimateChange#92]
We are interested to see if there are particular climate variables driving certain patterns in predictions (Great Basin & Midwest hotspots). First step is to find out where climate variable importance information is stored / could be stored / could be assessed.

**Comment by ezylstra** [comment]
Started a script in `src/summary` folder to calculate variable importance for a selected species in f60c3a88. A few notes:
- Generally, we should be able to extract the information needed to calculate variable importance from SDM objects saved in the `output/SDM` folder (contents of which live on the HPC now, I think). 
- Looks like we should have run the full RF models with the argument importance = TRUE. I'm going to add that option to the `run_rf() `function and make associated edits in the first 2 templates. Probably worth re-running template 2 and 3 at some point. (I won't close this issue until I've done that). 
- Calculating var importance for some of these models (e.g., gam, lasso) is not straightforward. While a permutation approach might be the best approach in theory, implementing that (via an R package or not) is difficult and computationally inefficient.  Instead, I've outlined approaches that are common, but less ideal and kind of "coarse".  I'm guessing it's probably ok for now.

**Comment by ezylstra** [comment]
Added importance argument to run_rf function in e5f2af45f7fc35a82960ccf659f94cdd37b8f864
